### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by jknowles** [zachmayer/caretEnsemble#32]
@zachmayer this package is working in production for me in a couple of places. I was thinking it would be nice to finish up some of the current features and build unit tests to make sure the core feature -- ensembling of classification and regression `caret` objects, stays stable and works. I'm a little nervous that some of the additions I have been making over in `Dev` cloud up the focus of the package more than they help. 

With that in mind I was thinking we could use this issue to brainstorm ideas for package extensions and prioritize them a bit based on needs. From my end I would say the top 4 things to improve are:
- [x] A unit test suite for all objects and their generics/methods
- [ ] Unit tests for the optimizers, with some edge cases
- [x] Make sure the predict method works in edge cases and arrive at some way to calculate prediction errors
- [x] Convenient print, plot, and summary methods for `caretEnsemble` and `caretList` objects

Then some "nice to have" features would be: 
- [x] Better variable importance calculations
- [ ] Speed up prediction performance (parallelize it somehow)

What do you think?
